// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package frontend

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets\icons\alphabetical.svg
var resourceAlphabeticalSvgData []byte
var resourceAlphabeticalSvg = &fyne.StaticResource{
	StaticName:    "assets\\icons\\alphabetical.svg",
	StaticContent: resourceAlphabeticalSvgData,
}

//go:embed assets\icons\collection_tab.svg
var resourceCollectiontabSvgData []byte
var resourceCollectiontabSvg = &fyne.StaticResource{
	StaticName:    "assets\\icons\\collection_tab.svg",
	StaticContent: resourceCollectiontabSvgData,
}

//go:embed assets\icons\icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "assets\\icons\\icon.png",
	StaticContent: resourceIconPngData,
}

//go:embed assets\icons\random.svg
var resourceRandomSvgData []byte
var resourceRandomSvg = &fyne.StaticResource{
	StaticName:    "assets\\icons\\random.svg",
	StaticContent: resourceRandomSvgData,
}

//go:embed assets\icons\youtube.svg
var resourceYoutubeSvgData []byte
var resourceYoutubeSvg = &fyne.StaticResource{
	StaticName:    "assets\\icons\\youtube.svg",
	StaticContent: resourceYoutubeSvgData,
}
