// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed internal\assets\alphabetical.svg
var resourceAlphabeticalSvgData []byte
var resourceAlphabeticalSvg = &fyne.StaticResource{
	StaticName:    "internal\\assets\\alphabetical.svg",
	StaticContent: resourceAlphabeticalSvgData,
}

//go:embed internal\assets\icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "internal\\assets\\icon.png",
	StaticContent: resourceIconPngData,
}

//go:embed internal\assets\playlist.svg
var resourcePlaylistSvgData []byte
var resourcePlaylistSvg = &fyne.StaticResource{
	StaticName:    "internal\\assets\\playlist.svg",
	StaticContent: resourcePlaylistSvgData,
}

//go:embed internal\assets\random.svg
var resourceRandomSvgData []byte
var resourceRandomSvg = &fyne.StaticResource{
	StaticName:    "internal\\assets\\random.svg",
	StaticContent: resourceRandomSvgData,
}

//go:embed internal\assets\youtube.svg
var resourceYoutubeSvgData []byte
var resourceYoutubeSvg = &fyne.StaticResource{
	StaticName:    "internal\\assets\\youtube.svg",
	StaticContent: resourceYoutubeSvgData,
}
