// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package resource

import "fyne.io/fyne/v2"

var WindowIcon = &fyne.StaticResource{
	StaticName: "icon.png",
	StaticContent: []byte(
		"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x80\x00\x00\x00\x80\x01\x03\x00\x00\x00\xf9\xf0\xf3\x88\x00\x00\x00\x01sRGB\x00\xae\xce\x1c\xe9\x00\x00\x00\x04gAMA\x00\x00\xb1\x8f\v\xfca\x05\x00\x00\x00\x06PLTE\x00\x00\x00\xff\xff\xff\xa5ٟ\xdd\x00\x00\x00\tpHYs\x00\x00\x12t\x00\x00\x12t\x01\xdef\x1fx\x00\x00\x01;IDATH\xc7\xed\xd51n\x860\f\x05\xe0\xa0\f\x8c\x1c\x81\xa3\xf0\x1f\xa5G\xe8ءj|\xb4p\x13\xa4^\x00\xa9C;\xa0\xa6~\xcf?\xc4d\xe9P\xb5R%2 \xeb\x1b\xf2l\x83D\xf8\x953\x94\xd3Y\x1b\x90\x16B\x03\x9f-l\x15\xf2\xfdJ\x85\xc5n\xe3s\x01\xe4T!\x13\xa6\nB\x18\x99g!\x84\x81\xa5\x85\x10z\x96\x80\x8f\x80Nsd\xc9Ԏб\x01\x86DB`\x03\f\x19\f\x12\x1a`\xd4h0\xa1\x01FM\x06\xdaH\b\xbc9\x11n=:b\b\x17\x94\x1f\xa2\x02Z_\xa2\xc1\xa3n\xb6\x03h\x8b\x84'\x85\b\xd0\xdd\x10\x9e\x15za\x88\xc1\xcb\x1d6m\x88\x90Dߎ\xd8<\x069h\x8b\x1a\xa2C\x19,\x06\u0603\xf8\x9d\x8an\xea\x04\x18\xc1\xc3\xc6!\x1dpi\x1eVl\xceÂ\xddz\x10l\xdf\x03B<`\xb4\x13`\xb4\n\xef\xa8\xf6o\f0\x17a\xc8\x01\x9a\xc1W|\x80\xee_\x86\no\x00\xa6\xee\v\"$\a\tP*Ȥ\x97v-\xc4\x13\xbc\x16\v9@\xab\xb1\xf8K\xb5\x9a<\xa0J\xc57\xb6\x7f\xc9n\xfc\xb9\x85r\xc1\x05\x17\xfc'8\xfd:\xff\x0e|\x1f\xf3\xf17\xdd\xcf\xfa\xddO\\\xe1\xc7'\x84/\xb9O\x88\xe0\x8bV>\x1e\x00\x00\x00\x00IEND\xaeB`\x82"),
}
var CollectionTabIcon = &fyne.StaticResource{
	StaticName: "collection_tab.svg",
	StaticContent: []byte(
		"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"128\" height=\"128\"><g stroke=\"#fcffe5\" stroke-width=\"3\"><path fill=\"#15a6e5\" d=\"M11 10h89v89H11zm0 0\"/><path fill=\"#fbe80b\" d=\"M27 28h89v89H27zm0 0\"/></g><path fill=\"#ff7f26\" d=\"m41 103 17-30 17 30Zm0 0\"/><circle r=\"17\" cx=\"86\" cy=\"60\" fill=\"#ffaec9\"/></svg>"),
}
var YouTubeIcon = &fyne.StaticResource{
	StaticName: "youtube.svg",
	StaticContent: []byte(
		"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 28.57 NaN\" pointer-events=\"none\" width=\"100%\" height=\"100%\" xmlns:v=\"https://vecta.io/nano\"><svg viewBox=\"0 0 28.57 20\" preserveAspectRatio=\"xMidYMid meet\"><path d=\"M27.973 3.123A3.58 3.58 0 0 0 25.447.597C23.22 0 14.285 0 14.285 0S5.35 0 3.123.597A3.58 3.58 0 0 0 .597 3.123C0 5.35 0 10 0 10s0 4.65.597 6.877a3.58 3.58 0 0 0 2.526 2.526C5.35 20 14.285 20 14.285 20s8.935 0 11.162-.597a3.58 3.58 0 0 0 2.526-2.526C28.57 14.65 28.57 10 28.57 10s-.002-4.65-.597-6.877z\" fill=\"red\"/><path d=\"M11.425 14.285L18.848 10l-7.422-4.285v8.57z\" fill=\"#fff\"/></svg></svg>"),
}
var AlphabeticalIcon = &fyne.StaticResource{
	StaticName: "alphabetical.svg",
	StaticContent: []byte(
		"<svg width=\"128\" height=\"128\" viewBox=\"0 0 16 16\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#fff\" class=\"bi bi-sort-alpha-up\"><path fill-rule=\"evenodd\" d=\"M10.082 5.629 9.664 7H8.598l1.789-5.332h1.234L13.402 7h-1.12l-.419-1.371zm1.57-.785L11 2.687h-.047l-.652 2.157z\"/><path d=\"M12.96 14H9.028v-.691l2.579-3.72v-.054H9.098v-.867h3.785v.691l-2.567 3.72v.054h2.645zm-8.46-.5a.5.5 0 0 1-1 0V3.707L2.354 4.854a.5.5 0 1 1-.708-.708l2-1.999.007-.007a.5.5 0 0 1 .7.006l2 2a.5.5 0 1 1-.707.708L4.5 3.707z\"/></svg>"),
}
var RandomIcon = &fyne.StaticResource{
	StaticName: "random.svg",
	StaticContent: []byte(
		"<svg width=\"64\" height=\"64\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"4\" y=\"4\" width=\"56\" height=\"56\" rx=\"10\" ry=\"10\" fill=\"none\" stroke=\"#fff\" stroke-width=\"4\"/><circle cx=\"20\" cy=\"20\" r=\"5\" fill=\"#fff\"/><circle cx=\"32\" cy=\"32\" r=\"5\" fill=\"#fff\"/><circle cx=\"44\" cy=\"44\" r=\"5\" fill=\"#fff\"/></svg>"),
}
