package resource

const KWindowTitle = "MeowyPlayer"
const KDownloadText = "Download"
const KUploadText = "Upload"
const KQueueText = "Queue"
const KCancelText = "Cancel"
const KCreateText = "Create"
const KDeleteText = "Delete"
const KSaveText = "Save"
const KEditText = "Edit"
const KHomeText = "Home"
const KCollectionsText = "Collections"
const KAccountText = "Account"
const KSettingsText = "Settings"
const KBackText = "Back"
const KSearchingText = "Searching"
const KAttemptsText = "Attempts"
const KSortMenuText = "Sort By"
const KMostRecentText = "Most Recent"
const KAlphabeticalText = "Alphabetical"
const KCreateAlbumText = "Create Album"
const KEditAlbumText = "Edit Album"
const KEnterTitleHint = "Enter title:"
const KDeleteConfirmationText = "Delete Confirmation"
const KSelectAlbumText = "(Select an album)"
const KRandomText = "Random"
const KOrderedText = "Ordered"
const KRepeatText = "Repeat"

const KDeleteAlbumTextTemplate = "Delete the album \"%v\" ?"
const KDeleteMusicTextTemplate = "Delete the music \"%v\" ?"
const KAlbumTipTextTemplate = "Songs: %v\n\nLast Edit: %v"
